### ISSUE TITLE
gock: cannot match any request

### ISSUE THREAD

**Issue by fgblomqvist** [h2non/gock#10]
I keep getting this error no matter what I do with this mock.
This is the mock:
```
gock.New("http://www.espn.com").
		Get("/nfl/player/gamelog/_/id/16733/year/2015/").
		Reply(200).
		File("testdata/espn_gamelog_2015.html")
```

And this is the error I get:
`Failed to query ESPN: Get http://espn.go.com/nfl/player/gamelog/_/id/16733/year/2015/: gock: cannot match any request"`

As you can see it's the exact same URL. What's wrong?

**Comment by h2non** [comment]
Thanks for reporting the issue. I'll try to debug that tomorrow and let you know (and also answer you with the other issue you opened).

**Comment by fgblomqvist** [comment]
Ah phew, I thought the project was dying, so glad it's not. It's really the most intuitive http mocker I've found. Thanks a lot for your continued effort!

**Comment by h2non** [comment]
Nah! I try to provide support as much as I can in my OSS projects, but sometimes I'm too busy to do that effectively. More specifically, I was on vacations, mostly travelling for a couple of weeks until today. I'll give you a definitive solution soon.

**Comment by h2non** [comment]
I can reproduce your issue. This is my test code:
```go
package main

import (
	"fmt"
	"net/http"

	"gopkg.in/h2non/gock.v1"
)

func main() {
	defer gock.Disable()

	gock.New("http://www.espn.com").
		Get("/nfl/player/gamelog/_/id/16733/year/2015/").
		Reply(204)

	res, err := http.Get("http://www.espn.com/nfl/player/gamelog/_/id/16733/year/2015/")
	fmt.Printf("Error: %s\n", err)
	fmt.Printf("Status: %d\n", res.StatusCode)
}
```

Run it via:
```go
$ go run test.go
```

**Comment by fgblomqvist** [comment]
Sorry for my lengthy absence. In the end, the fault turned out to lie on my end (mistyped URL). I hope I did not cause too much headache for you. I appreciate your help!

**Comment by h2non** [comment]
No problem.

**Comment by yinjianping07** [comment]
the host you requested is `espn.go.com` instead of `www.espn.com`, you can debug to see what happend.
