### ISSUE TITLE
AddMatch

### ISSUE THREAD

**Issue by wshelly** [h2non/gock#20]
AddMatch only use once in a go program?

package main

import (
	"fmt"
	"net/http"
	"regexp"
	"gopkg.in/h2non/gock.v1"
)

func test_a() {
	defer gock.Off()

	gock.New("http://httpbin.org").Get("/").
		AddMatcher(func(req *http.Request, ereq *gock.Request) (bool, error) {
		matched, err := regexp.MatchString("/aa/[A-Za-z0-9]{6}/ii/[A-Za-z0-9]{6}/calculator", req.URL.Path)
		return matched && "GET" == req.Method, err
	}).
		Reply(204).
		SetHeader("Server", "gock")

	res, err := http.Get("http://httpbin.org/aa/123456/ii/123456/calculator")
	if err != nil {
		fmt.Errorf("Error: %s", err)
	}

	fmt.Printf("Status: %d\n", res.StatusCode)
	fmt.Printf("Server header: %s\n", res.Header.Get("Server"))
}

func test_b() {
	defer gock.Off()
	gock.New("http://httpbin.org").
		Get("/application").
		Reply(200).
		SetHeader("Server", "gockbin")

	res, err := http.Get("http://httpbin.org/application")
	if err != nil {
		fmt.Errorf("Error: %s", err)
	}
	fmt.Printf("Status: %d\n", res.StatusCode)
	fmt.Printf("Server header: %s\n", res.Header.Get("Server"))
}

func main() {
	test_a()
	test_b()
}

**Comment by wshelly** [comment]
I use Filter solve this problem

`func filter(req *http.Request) bool {
	matched, _ := regexp.MatchString("/aa/[A-Za-z0-9]{6}/ii/[A-Za-z0-9]{6}/calculator", req.URL.Path)
	return matched && "GET" == req.Method
}

func test_a() {
	defer gock.Off()

	gock.New("http://httpbin.org").Filter(filter).
		Reply(204).
		SetHeader("Server", "gock")

	res, err := http.Get("http://httpbin.org/aa/123456/ii/123456/calculator")
	if err != nil {
		fmt.Errorf("Error: %s", err)
	}

	fmt.Printf("Status: %d\n", res.StatusCode)
	fmt.Printf("Server header: %s\n", res.Header.Get("Server"))

}`

**Comment by h2non** [comment]
@JusbeR It's instended. If you want to clean any unmatched request from the mock store, you should call `gock.OffAll()` instead.

**Comment by JusbeR** [comment]
Hmm, it feels like I am not getting something here now. If I run this:
```
package main

import (
	"log"
	"net/http"

	"gopkg.in/h2non/gock.v1"
)

func NewGockClient() *http.Client {
	c := &http.Client{Transport: &http.Transport{}}
	gock.InterceptClient(c)
	return c
}

func failingMatcher() {
	log.Println("Failing matcher")
	defer gock.OffAll()
	gock.New("https://example.com").
		Get("/api").
		AddMatcher(func(req *http.Request, ereq *gock.Request) (bool, error) { return false, nil }).
		Reply(200).
		BodyString("{}")

	c := NewGockClient()
	req, _ := http.NewRequest("GET", "https://example.com/api", nil)

	_, err := c.Do(req)
	if err != nil {
		log.Println("Failed:", err)
	} else {
		log.Println("Ok")
	}
}
func noMatcher() {
	log.Println("No matcher")
	defer gock.OffAll()
	gock.New("https://example.com").
		Get("/api").
		Reply(200).
		BodyString("{}")

	c := NewGockClient()
	req, _ := http.NewRequest("GET", "https://example.com/api", nil)

	_, err := c.Do(req)
	if err != nil {
		log.Println("Failed:", err)
	} else {
		log.Println("Ok")
	}
}
func main() {
	noMatcher()
	failingMatcher()
	noMatcher()
}
```
I get:
```
2018/08/15 08:47:34 No matcher
2018/08/15 08:47:34 Ok
2018/08/15 08:47:34 Failing matcher
2018/08/15 08:47:34 Failed: Get https://example.com/api: gock: cannot match any request
2018/08/15 08:47:34 No matcher
2018/08/15 08:47:34 Failed: Get https://example.com/api: gock: cannot match any request
```
Which should not happen after the `OffAll` call?

**Comment by JusbeR** [comment]
It does this probably because we modify the [DefaultMathcer](https://github.com/h2non/gock/blob/master/matcher.go#L24). I tried to add `DefaultMatcher = NewMatcher()` to [OffAll](https://github.com/h2non/gock/blob/master/gock.go#L92), to check my theory and to me the behavior becomes more logical. But I speak only about this one case. Dunno if changing this breaks some other consistent behavior that I am not aware of.

**Comment by h2non** [comment]
@ods94065 Thanks for the comment here. I review the issue and your points makes sense to me. I don't recall why I have decided to modify package-level state to be honest, but reviewing it now, I think it was a design mistake.

Options 1 and 2 seems reasonable to me and it's pretty much what I had in mind. Will push a fix soon. I might have some negative side-effects to some users, but I will not consider it a breaking change.

The good thing about the option 2 is that users that want to have globally shared matches can still rely on it by using `gock.DefaultMatcher` methods.

**Comment by Funcan** [comment]
@h2non Any progress on this? I just hit the same bug, and I'm happy to spend some time fixing it using one of the above suggestion if that helps
