### ISSUE TITLE
Reset unmatchedRequests during Off()

### ISSUE THREAD

**Issue by nikolay-turpitko** [h2non/gock#24]
I think, it could be nice to reset unmatchedRequests during Off() so that unit tests will be more independent of each other.

**Comment by h2non** [comment]
In gock@v1.0.5 you can now use: ``gock.CleanUnmatchedRequests()`` or ``gock.OffAll()``, which behaves like ``gock.Off()`` + ``gock.CleanUnmatchedRequests``.
