### ISSUE TITLE
Multiple response headers with same name are not set on http response

### ISSUE THREAD

**Issue by steinfletcher** [h2non/gock#35]
I am trying to set multiple cookies with the same name on the gock response, but it always seems to only set the first cookie on the response object.

Am I doing something wrong - is there a better way to set cookies?

The mergeHeaders function appears to be the culprit. I have a solution and test here: https://github.com/steinfletcher/gock/commit/75ea39d311ffa5c435ffb9a015de2480c980ff55

Thanks

**Comment by h2non** [comment]
Right, in such case multiple headers should exist with the same key. Would you mind sending a PR? Thank you.

**Comment by steinfletcher** [comment]
Submitted PR, but a test fails in CI that I can't reproduce locally. Seems unrelated.

**Comment by h2non** [comment]
Thanks for the PR!

New patch version is now available. Try upgrading the package.

**Comment by steinfletcher** [comment]
Thanks @h2non!
