### ISSUE TITLE
when i access the uri twice in one test, i must gock.New(Uri) twice too

### ISSUE THREAD

**Issue by seanjoe** [h2non/gock#56]
my func is

{
        defer gock.Off()
	gock.New("https//url.com").Get("path").Reply(200)
	gock.New("https//url.com").Get("path").Reply(200)
	gock.Observe(gock.DumpRequest)
         // some test  in the func maybe access url twice or more
}

if i use once, other access got Matches: false
why

**Comment by h2non** [comment]
You could use:
```go
gock.New("https//url.com").Get("path").Reply(200).Times(2)
```

For more information, see the docs:
https://godoc.org/github.com/h2non/gock#Request.Times

**Comment by seanjoe** [comment]
thank you！I think it is a temporary solution, i must estimate the times before use or set a big number in haste.

**Comment by h2non** [comment]
Alternatively, you can use `.Persist()` method, which will guarantee the mock is alive unless you explicitly turn `gock` off. See:
https://godoc.org/github.com/h2non/gock#Request.Persist
