### ISSUE TITLE
gopkg url leads to wrong (older?) version

### ISSUE THREAD

**Issue by fgblomqvist** [h2non/gock#6]
I installed gock using the specified gopkg.in url:
`go get -u gopkg.in/h2non/gock.v0`
And I'm pretty sure it installed a really old version, because .Get() did not exist. Are we supposed to specify the version ourselves? If so, maybe add a hint about that (for the people like me that have not come across a gopkg url before)?

**Comment by h2non** [comment]
Srry for the inconvenience here. I'll bumo gock to v1.0 today since the package is now stable enough. I'll let you know.

**Comment by h2non** [comment]
Major version `v1` was released. Feel free to update it.
```bash
go get -u gopkg.in/h2non/gock.v1
```
