### ISSUE TITLE
SetError not implemented properly

### ISSUE THREAD

**Issue by fgblomqvist** [h2non/gock#7]
When using this gock:
`gock.New("http://www.google.com"). Get("/").Reply(500).SetError(errors.New("Internal Server Error"))`

The following line is printed:
`2016/04/18 12:14:03 RoundTripper returned a response & error; ignoring response`

I'm guessing the RoundTripper is supposed to return a nil response when the error is set? Or I am supposed to set it to nil somehow?

**Comment by h2non** [comment]
That case should be mitigated. Will fix it in asap. Thanks for reporting.

**Comment by h2non** [comment]
Fixed. Try updating the package:
```bash
go get -u gopkg.in/h2non/gock.v1
```
